### ISSUE TITLE
Folders / A Way to Organize Rules

### ISSUE THREAD

**Issue by Penguin-Powered** [terahlunah/monke#3]
Hello!

I want to say that I love using your tool, and I am adding many rules. Unfortunately, it is hard to stay organized and not have to scroll a lot. I want to propose the addition of folders.

Folders would allow you to organize and collapse/hide rules. I would also want to name folders so that, when they are collapsed, I know what rules they contain.

Thank you for reading and for putting so much effort into Monke!

**Comment by terahlunah** [comment]
Hey,

Thanks for the feedback!

I'm not quite convinced folders are a good idea for the UX as it's already quite complex. But most importantly it's not trivial to implement which means I don't have the time to do something like that for now :/

That being said, I made some changes and added a `Collapse` button on rules (right next to the `Reorder button`) to hopefully improve the situation on your side.

Here's a preview version with the new feature, let me know what you think!
https://monke-git-collapsible-rules-terahs-projects.vercel.app/

**Comment by terahlunah** [comment]
Glad you like it!

I just merged the PR, it's available on the main url now, enjoy!

No worry, I'll close the issue now that the work is done.
